<?php

namespace ClubBundle\Repository;

use ClubBundle\Entity\competition;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function Findtop()
    {
        $query=$this->getEntityManager()->createQuery("SELECT i FROM ClubBundle:Club i 
order by i.solde DESC");
        $query->setMaxResults(5);
        return $query->getResult();
    }

}
