annonce_index:
    path:     /
    defaults: { _controller: "PubBundle:Annonce:index" }
    methods:  GET
annonce_index1:
    path:     /
    defaults: { _controller: "PubBundle:Annonce:index1" }
    methods:  GET

annonce_show:
    path:     /{id}/show
    defaults: { _controller: "PubBundle:Annonce:show" }
    methods:  GET




annonce_new:
    path:     /new
    defaults: { _controller: "PubBundle:Annonce:new" }
    methods:  [GET, POST]

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "PubBundle:Annonce:edit" }
    methods:  [GET, POST]

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "PubBundle:Annonce:delete" }
    methods:  DELETE
