<?php

namespace PaiementBundle\Repository;

/**
 * MethodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MethodeRepository extends \Doctrine\ORM\EntityRepository
{
}
