v_back_homepage:
    path:     /
    defaults: { _controller: VBackBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: VBackBundle:Default:layout }
gestion_annonce:
    path:     /gestion_annonce
    defaults: { _controller: VBackBundle:Default:gestion_annonce }

gestion_commande:
    path:     /gestion_commande
    defaults: { _controller: CommandeBundle:Commande:afficher}

gestion_livraison:
    path:     /gestion_livraison
    defaults: { _controller: CommandeBundle:livraison:afficher }
gestion_paiement:
    path:     /gestion_paiement
    defaults: { _controller: PaiementBundle:Paiement:afficherP }
gestion_evenement:
    path:     /gestion_evenement
    defaults: { _controller: EventBundle:CategorieREC:read }

gestion_publicite:
    path:     /gestion_publicite
    defaults: { _controller: PubBundle:Pub:read }
gestion_publicite2:
    path:     /gestion_publicite2
    defaults: { _controller: PubBundle:Pub:read1 }
annonce_front:
    path:     /annonce_front
    defaults: { _controller: PubBundle:Annonce:index1 }
gestion_pdf:
    path:     /pdf
    defaults: { _controller: EventBundle:Reclamation:pdf}
gestion_pdf1:
    path:     /pdf1/{id}
    defaults: { _controller: PubBundle:Annonce:pdf}
gestion_reclamation:
    path:     /gestion_reclamation
    defaults: { _controller: EventBundle:Reclamation:read }
gestion_reclamation_ar:
    path:     /gestion_reclamation_ar
    defaults: { _controller: EventBundle:Reclamation:readar }
login:
    path:     /loginA
    defaults: { _controller: VBackBundle:Default:login }
accuil:
    path:     /accuil
    defaults: { _controller: VBackBundle:Default:accuil }
gestion_client:
    path:     /gestion_client
    defaults: { _controller: UserBundle:Client:afficher }
gestion_partenaire:
    path:     /gestion_partenaire
    defaults: { _controller: UserBundle:Partenaire:afficher }
gestion_administrateur:
    path:     /gestion_administrateur
    defaults: { _controller: UserBundle:Admin:afficher }
gestion_stock:
    path:     /gestion_stock/{user_id}
    defaults: { _controller: GProduitBundle:Produit:afficher }
gestion_categorie:
    path:     /gestion_categorie
    defaults: { _controller: GProduitBundle:Categorie:afficher }

gestion_club:
    path:     /gestion_club
    defaults: { _controller: ClubBundle:Cclub:read }