competition_index:
    path:     /
    defaults: { _controller: "ClubBundle:competition:index" }
    methods:  GET

competition_show:
    path:     /{id}/show
    defaults: { _controller: "ClubBundle:competition:show" }
    methods:  GET

competition_new:
    path:     /new
    defaults: { _controller: "ClubBundle:competition:new" }
    methods:  [GET, POST]

competition_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:competition:edit" }
    methods:  [GET, POST]

competition_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:competition:delete" }
    methods:  DELETE

